### PR TITLE
Add --align-object-properties option

### PR DESCRIPTION
**Pull request by josephfrazier**
As discussed in https://github.com/prettier/prettier/issues/1622#issuecomment-302442135

Since this is based off of upstream prettier's master branch, that should be merged first to eliminate conflicts. The meaningful changes in this PR are in only the last handful of commits (the ones not in upstream master).

### CODE REVIEW

**Comment by rhengles** [comment]
Thank you! I will do that 👍

**Comment by rhengles** [comment]
I've updated the master branch, can you please rebase? Thanks! 😊

**Comment by josephfrazier** [comment]
I just fixed the conflicts. Not sure why a test failed, but it seems unrelated to this change: https://travis-ci.org/arijs/prettier-miscellaneous/jobs/234104749#L1027-L1032

**Comment by rhengles** [comment]
Alright, I'll just merge it and try on master. 👍

**Comment by nmaxcom** [comment]
This is not on the [website](https://prettier.github.io/prettier/) yet though, is it?

**Comment by langdonx** [comment]
@nmaxcom No, and it won't be.  That's the main version of prettier.  See https://github.com/arijs/prettier-miscellaneous/issues/16

**Pull request merged**
