### PR TITLE
fix: break-before-else

### PR DESCRIPTION
**Pull request by langdonx**
I ended up doing what I described here: https://github.com/arijs/prettier-miscellaneous/issues/15.  I imagine nobody else is really championing that feature though, so I figured I'd submit what seems to work for my edge cases.

This change leaves behind dead code (`isCurlyBracket`, `isEmptyBlock`), but there is another dead method (`shouldPrintSameLine`) and a lot of inspections in `printer.js` are failing.  Not sure how you feel about that.  I can remove them if you like.

### CODE REVIEW

**Comment by rhengles** [comment]
Thank you, this is marvelous! I'll merge this immediately, but I want to know what you mean by "inspections failing".

**Comment by langdonx** [comment]
By inspections, I just mean that there are a bunch of ESLint errors.  They show up as red errors in Viscose.  They are also part of the reason that the Travis builds are failing.  You can see the ESLint errors at the top:

https://travis-ci.org/arijs/prettier-miscellaneous/jobs/244658166

I can sort most of these out in a PR if you like.  We could/should get the build healthy again and then you'll be able to more easily trust future PRs.

**Comment by langdonx** [comment]
@rhengles Holler when you publish this!  Hopefully @remimarsal can then update [Prettier Now](https://marketplace.visualstudio.com/items?itemName=remimarsal.prettier-now).

**Comment by remimarsal** [comment]
@langdonx Of course 😜 @rhengles bump me when you release next version

**Comment by rhengles** [comment]
@langdonx @remimarsal https://www.npmjs.com/package/prettier-miscellaneous v1.5.2 was just released! 🎉

**Comment by remimarsal** [comment]
Thanks @rhengles! I eventually added prettier misc as an external library so I can stay in sync with latest features regardless of npm package version

**Pull request merged**
